name: CI

on: [push]

jobs:
  macos:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and Test
        run: swift test
